module.exports = {
  "ADMIN": {
    "keywords": [
      "admin",
      "quản trị viên"
    ]
  },
  "VANTHU": {
    "keywords": [
      "văn thư",
      "vt",
      "văn thư cục",
      "văn thư bảo mật",
      "bảo mật lưu trữ",
      "văn thư lưu trữ"
    ]
  },
  "VAN_THU_CUC": {
    "keywords": [
      "văn thư cục"
    ]
  },
  "GIAM_DOC": {
    "keywords": [
      "giám đốc",
      "tổng giám đốc",
      "giám đốc cn",
      "giám đốc trung tâm",
      "giám đốc nhân sự",
      "chủ tịch kiêm giám đốc",
      "chủ tịch hđqt",
      "chủ tịch hội đồng quản trị",
      "chủ tịch",
      "chính ủy",
      "tham mưu trưởng",
      "tmt",
      "phó tổng giám đốc",
      "cn chính trị",
      "đại phó",
      "hải đoàn trưởng",
      "phó chủ tịch hội đồng thành viên",
      "phó chủ tịch hđtv",
      "thành viên hđtv",
      "thành viên hội đồng thành viên",
      "thư ký thường trực hội đồng thành viên",
      "thư ký tổng giám đốc",
      "lãnh đạo",
      "tgđ",
      "tgđ"
    ]
  },
  "PHO_GIAM_DOC": {
    "keywords": [
      "phó giám đốc",
      "phó gđ",
      "phó gd",
      "phó chính ủy",
      "phó tham mưu trưởng",
      "ptgđ",
      "phó tổng giám đốc",
      "phó chủ tịch",
      "ptgd"
    ]
  },
  "CHANH_VAN_PHONG": {
    "keywords": [
      "chánh văn phòng",
      "cvp"
    ]
  },
  "PHO_CHANH_VAN_PHONG": {
    "keywords": [
      "phó chánh văn phòng"
    ]
  },
  "TRUONG_PHONG": {
    "keywords": [
      "trưởng phòng",
      "tp",
      "trưởng ban",
      "trưởng trung tâm",
      "trưởng chi nhánh",
      "trưởng ter",
      "quản đốc",
      "kế toán trưởng",
      "chủ nhiệm",
      "phụ trách phòng",
      "tp tài chính",
      "tp.điều độ",
      "tp.tchc",
      "quyền tpth",
      "trưởng dp",
      "dpa",
      "trưởng khu",
      "trưởng ban thương vụ",
      "trưởng ban giao nhận",
      "trạm trưởng",
      "trưởng trạm",
      "thuyền trưởng",
      "máy trưởng",
      "máy trưởng tàu khách",
      "xe trưởng",
      "trưởng depot",
      "trưởng văn phòng đại diện",
      "trưởng ttpp",
      "trưởng đhsx",
      "trưởng tmn",
      "xưởng trưởng",
      "trung đội trưởng",
      "trưởng trực ban",
      "trưởng khu kho hàng"
    ]
  },
  "PHO_TRUONG_PHONG": {
    "keywords": [
      "phó trưởng phòng",
      "ptp",
      "phó phòng",
      "phó ban",
      "phó trung tâm",
      "phó trưởng trung tâm",
      "phó trưởng chi nhánh",
      "phó ter",
      "phó terminal",
      "phó chủ nhiệm",
      "hải đội phó",
      "phó quản đốc",
      "p.hđt",
      "pp kế toán",
      "tổ trưởng",
      "đội trưởng",
      "trưởng kho",
      "trưởng ca",
      "bếp trưởng",
      "tiểu đội trưởng",
      "quản lý bếp",
      "tbsx",
      "trưởng tbsx",
      "trưởng khu kh",
      "xưởng phó",
      "phó chi nhánh",
      "phó depot",
      "phó trưởng khu kho hàng",
      "trung đội phó",
      "thuyền phó",
      "máy phó",
      "sĩ quan máy",
      "sĩ quan boong",
      "giám sát ca",
      "giám sát công trình",
      "giám sát chất lượng",
      "phó trưởng trực ban"
    ]
  },
  "CAN_BO": {
    "keywords": [
      "nhân viên",
      "chuyên viên",
      "kế toán",
      "trợ lý",
      "i tá",
      "y sĩ",
      "bác sĩ",
      "bác sỹ",
      "dược tá",
      "quân y",
      "y tế",
      "điều dưỡng",
      "kỹ thuật viên nha khoa",
      "kỹ thuật viên y học cổ truyền",
      "ktv x quang",
      "cấp phát thuốc",
      "lái xe",
      "lái canô",
      "lái cẩu",
      "lái máy",
      "lễ tân",
      "nhân sự",
      "kinh doanh",
      "logistics",
      "logistic",
      "kỹ thuật",
      "kỹ sư",
      "tổ phó",
      "đội phó",
      "phó kho",
      "tiểu đội phó",
      "phó khu",
      "thư ký",
      "thu ngân",
      "thủ quỹ",
      "thủ quĩ",
      "thủ kho",
      "thống kê",
      "điều độ",
      "điều hành",
      "kiểm soát",
      "kiểm soát viên",
      "thương vụ",
      "chứng từ",
      "giao nhận",
      "trực ban",
      "tiền lương",
      "định mức",
      "nhân viên kt",
      "nhân viên kd",
      "nhân viên tc",
      "nhân viên an toàn",
      "nhân viên kỹ thuật",
      "nhân viên truyền thông",
      "nhân viên cảng vụ",
      "nhân viên kho vật tư",
      "nhân viên tiếp liệu",
      "cán bộ an toàn",
      "depot",
      "sales",
      "marketing",
      "kh - kd",
      "hc - vt",
      "tclđ",
      "cnkt",
      "cnhc",
      "cnct",
      "phct",
      "tl tp",
      "nv kh - kt",
      "thư viện",
      "tổ chức hành chính",
      "quản trị mạng",
      "quản trị hệ thống",
      "nấu ăn",
      "bộ phận",
      "văn phòng",
      "hành chính",
      "pháp chế",
      "khai thác",
      "an toàn lao động",
      "bảo hộ lao động",
      "công nghệ thông tin",
      "lập trình",
      "điện tử",
      "điện - điện tử",
      "an ninh mạng",
      "bảo vệ",
      "tạp vụ",
      "vệ sinh",
      "phục vụ",
      "dọn buồng",
      "giữ xe",
      "thuyền viên",
      "thủy thủ",
      "hoa tiêu",
      "chiến sĩ",
      "học việc",
      "thử việc",
      "tập sự",
      "công đoàn",
      "quan hệ",
      "dịch vụ khách hàng",
      "chăm sóc khách hàng",
      "báo giá",
      "phụ xe",
      "thợ",
      "sửa chữa",
      "bảo trì",
      "bảo dưỡng",
      "thị trường",
      "kho hàng",
      "quản lý vật tư",
      "quản lý thiết bị",
      "quản lý tàu thuyền",
      "quản lý xe máy",
      "quản lý bếp ăn",
      "quản lý kỹ thuật",
      "quản lý dv",
      "lao động - chính sách",
      "lao động - tiền lương",
      "đầu tư xây dựng",
      "đầu tư thiết bị",
      "tuyên huấn",
      "nhà hàng",
      "sản lượng",
      "sản xuất",
      "hiện trường",
      "công vụ",
      "công tác cầu cảng",
      "huấn luyện",
      "đào tạo",
      "doanh trại",
      "điện công nghiệp",
      "điện - nước",
      "phòng chống cháy nổ",
      "cứu hộ",
      "tư vấn",
      "khai báo hq",
      "phô tô",
      "thiết bị đầu cuối",
      "thành viên",
      "vi tính",
      "vận hành",
      "thanh lý",
      "kiểm hóa",
      "nghiệp vụ",
      "điều tàu",
      "làm hàng",
      "đối ngoại",
      "giám định",
      "chính sách",
      "xử lý đơn hàng",
      "chấm bay",
      "vá vỏ xe",
      "lập sơ đồ",
      "phân tích",
      "tổng hợp",
      "kế hoạch sx",
      "cẩu hàng rời",
      "khối hỗ trợ",
      "máy ii",
      "cảng vụ",
      "phát hành",
      "tiếp nhận",
      "vi tính cổng",
      "vi tính tổng hợp",
      "cán bộ"
    ]
  }
};