const path = require('path');
const fs = require('fs');

const configPath = path.join(__dirname, 'sync-config.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

// ROLE MAPPINGS
const ADMIN_KEYWORDS           = config.ROLE_MAPPINGS.ADMIN.KEYWORDS;
const ROLES_ADMIN            = config.ROLE_MAPPINGS.ADMIN.ROLES;

const GIAMDOC_KEYWORDS         = config.ROLE_MAPPINGS.GIAM_DOC.KEYWORDS;
const ROLES_GIAM_DOC         = config.ROLE_MAPPINGS.GIAM_DOC.ROLES;

const PHO_GIAMDOC_KEYWORDS     = config.ROLE_MAPPINGS.PHO_GIAM_DOC.KEYWORDS;
const ROLES_PHO_GIAM_DOC     = config.ROLE_MAPPINGS.PHO_GIAM_DOC.ROLES;

const TRUONGPHONG_KEYWORDS     = config.ROLE_MAPPINGS.TRUONG_PHONG.KEYWORDS;
const ROLES_TRUONG_PHONG     = config.ROLE_MAPPINGS.TRUONG_PHONG.ROLES;

const PHO_TRUONGPHONG_KEYWORDS = config.ROLE_MAPPINGS.PHO_TRUONG_PHONG.KEYWORDS;
const ROLES_PHO_TRUONG_PHONG = config.ROLE_MAPPINGS.PHO_TRUONG_PHONG.ROLES;

const VANTHUCUC_KEYWORDS       = config.ROLE_MAPPINGS.VAN_THU_CUC.KEYWORDS;
const ROLES_VAN_THU_CUC      = config.ROLE_MAPPINGS.VAN_THU_CUC.ROLES;

const VANTHU_KEYWORDS          = config.ROLE_MAPPINGS.VAN_THU.KEYWORDS;
const ROLES_VAN_THU          = config.ROLE_MAPPINGS.VAN_THU.ROLES;

const NHANVIEN_KEYWORDS        = config.ROLE_MAPPINGS.NHAN_VIEN.KEYWORDS;
const ROLES_DEFAULT          = config.ROLE_MAPPINGS.NHAN_VIEN.ROLES;

// OUTGOING SYNC CONFIG
const USER_PAREN_DEFAULT     = config.OUTGOING_SYNC_CONFIG.USER_PAREN_DEFAULT;
const BEGIN_LIMIT            = config.OUTGOING_SYNC_CONFIG.BEGIN_LIMIT;
const COMPLETED_LIMIT        = config.OUTGOING_SYNC_CONFIG.COMPLETED_LIMIT;

// Status Mapping constants
const TRANG_THAI_KHOI_TAO                      = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_KHOI_TAO;
const TRANG_THAI_XU_LY_CHINH_CHI_DAO           = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_XU_LY_CHINH_CHI_DAO;
const TRANG_THAI_DA_XU_LY_CHI_DAO              = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_DA_XU_LY_CHI_DAO;
const TRANG_THAI_CHO_HOAN_THANH_CHI_DAO        = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_CHO_HOAN_THANH_CHI_DAO;
const TRANG_THAI_XU_LY_CHINH_XLC               = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_XU_LY_CHINH_XLC;
const TRANG_THAI_HOAN_THANH_CHI_DAO            = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_HOAN_THANH_CHI_DAO;
const TRANG_THAI_THU_HOI                       = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_THU_HOI;
const TRANG_THAI_TRINH_XL_TRUONG_PHONG_SO_LOAI = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_TRINH_XL_TRUONG_PHONG_SO_LOAI;
const TRANG_THAI_TRA_LAI                       = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_TRA_LAI;
const TRANG_THAI_VAN_THU_TRINH_SL_HOANTHANH    = config.OUTGOING_SYNC_CONFIG.STATUS_TABS.TRANG_THAI_VAN_THU_TRINH_SL_HOANTHANH;

module.exports = {
  ADMIN_KEYWORDS,
  ROLES_ADMIN,
  GIAMDOC_KEYWORDS,
  ROLES_GIAM_DOC,
  PHO_GIAMDOC_KEYWORDS,
  ROLES_PHO_GIAM_DOC,
  TRUONGPHONG_KEYWORDS,
  ROLES_TRUONG_PHONG,
  PHO_TRUONGPHONG_KEYWORDS,
  ROLES_PHO_TRUONG_PHONG,
  VANTHUCUC_KEYWORDS,
  ROLES_VAN_THU_CUC,
  VANTHU_KEYWORDS,
  ROLES_VAN_THU,
  NHANVIEN_KEYWORDS,
  ROLES_DEFAULT,
  USER_PAREN_DEFAULT,
  BEGIN_LIMIT,
  COMPLETED_LIMIT,
  TRANG_THAI_KHOI_TAO,
  TRANG_THAI_XU_LY_CHINH_CHI_DAO,
  TRANG_THAI_DA_XU_LY_CHI_DAO,
  TRANG_THAI_CHO_HOAN_THANH_CHI_DAO,
  TRANG_THAI_XU_LY_CHINH_XLC,
  TRANG_THAI_HOAN_THANH_CHI_DAO,
  TRANG_THAI_THU_HOI,
  TRANG_THAI_TRINH_XL_TRUONG_PHONG_SO_LOAI,
  TRANG_THAI_TRA_LAI,
  TRANG_THAI_VAN_THU_TRINH_SL_HOANTHANH
};
